"bug":
  - '^[Ff]ix(\(.*\))?:?.*'
"chore":
  - '^[Cc]hore(\(.*\))?:?.*'
"documentation":
  - '^[Dd]ocs?(\(.*\))?:?.*'
"enhancement":
  - '^[Rr]efactor(\(.*\))?:?.*'
"feature":
  - '^[Ff]eat(\(.*\))?:?.*'

