---
apiVersion: v1
kind: Pod
metadata:
  namespace: test-dra
  name: pod-1
spec:
  containers:
  - name: ctr0
    image: ubuntu:24.04
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      requests:
        cpu: 1
      limits:
        cpu: 1
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    resourceClaimName: double-gpu-0
